### ISSUE TITLE
Launcher app

### ISSUE THREAD

**Issue by cmder-Jumpy** [gaussandhisgun/scrcpy-appcast#1]
Not really a problem, but is it necessary to download the launcher app in order for this to work or is the app just to go somewhere specific in an app. And if the app is needed in order for this to work is there any known alternatives? (:

**Comment by gaussandhisgun** [comment]
Launcher is needed only to find out package/activity names. You can freely use any other activity viewer app if you know any, or if you dont, you can just run `./create-app.sh Screen 480 800 - -`, then open the script in any preferred text editor, swap 40 to 0 in the last line and just use this script to cast virtual screen with default Google's launcher for external screens. Or github.com/farmerbb/taskbar (if configured).
